# This workflow will test a Cucumber Java project with Maven.

name: Java CI/CD with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Windows-Run:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test
